### ISSUE TITLE
Skyscraper does not preserve any emulationstation metadata

### ISSUE THREAD

**Issue by HumanRob** [muldjord/skyscraper#117] opened 2019-02-11 15:21 UTC
**Describe the bug**
skyscraper does not preserve emulationstation metadata, as mentioned in the release notes for Version 2.8.0. After running Skyscraper against any platform, all lastplayed, favorite and playcount attributes for that platform are gone.

**To Reproduce**
Play a game via emulationstation. Close emulationstation. View the system's gamelist.xml . Observe the lastplayed and playcount attributes.
Run skyscraper against the system: Skyscraper -p segacd --videos --symlink
View the system's gamelist.xml . The lastplayed and playcount attributes are gone.

**Special circumstances**
None that I can think of

**Terminal output**
If applicable, add terminal output to help visualize your problem.

**Technical information**
 - Skyscraper version: [e.g. 3.0.1]
 - Internet connection: wifi
 - OS: RetroPie
 - OS Version: 4.4

**Additional context**
This has been happening for a while, not just the latest release. It's become a bigger problem now as I'd like to update all platforms to save on disk space but I don't want to lose my last played or favourites lists in emulation station.

**Comment by muldjord** [comment] 2019-02-11 21:21
Maybe this got broken at some point, I'll look into it when I get the time.

**Comment by muldjord** [comment] 2019-02-11 21:34
I can't reproduce this, it works absolutely fine for me. I just created a game list with `Skyscraper -p mastersystem --videos --symlink`. Then I added `<playcount>20</playcount>` to one of the entries and saved the file. Then I rescraped with the same command, opened up the new game list, and the `<playcount>20</playcount>` is still there as expected.

When Skyscraper starts it will show the output `Trying to parse and load existing game list metadata...`. Does it say `Success!` just after that?
If you have any more info you can provide me let me know.

**Comment by muldjord** [comment] 2019-02-11 21:48
Just tested this on my other setup and here it disappears as you describe. I'll look into this, stay tuned.

EDIT: I've found the culprit, I'll fix this in the next release. Workaround is to disable the use of relative paths. This messes with how I compare the entries internally where one suddenly has a relative path and the one I compare with doesn't. So they don't match and the data isn't preserves.

**Comment by muldjord** [comment] 2019-02-11 22:37
This has now been fixed for most cases. There are edge cases where this won't work. For instance, if you have a psx .cue file inside of a subfolder and you move this file to the parent folder, it will no longer preserve the data for that file since it changes inside ES from a `<folder>` node to a `<game>` node by moving it. But if people decide to move their files around like that, I think it should be expected that metadata will be lost since the entry is basically no longer the same. It will work for non-psx files though so this is only an issue with iso-based files.

**Comment by HumanRob** [comment] 2019-02-12 09:05
Thanks for looking into this so quickly! As an end user I wouldn't expect metadata to be preserved when moving files to different locations so that seems reasonable to me.

**Comment by HumanRob** [comment] 2019-02-25 16:40
So I've tried this out on the latest version (3.0.4) and for me the metadata still seems to get lost.
As above, if a gamelist.xml contains some emulationstation specific meta data (e.g. lastplayed, playcount), if I run skyscraper (e.g. Skyscraper -p segacd --videos --symlink ), this information is missing from the gamelist afterwards. The game files haven't been moved around at all. 

I've checked the output as it runs, some details that stood out:
the version is shown as v3.0.4, 
It says "Trying to parse and load existing game list metadata... Success!"
On the part where each game is listed along with its metadata, none of the emulationstation metadata is shown (e.g. platform, Developer, Ages etc are shown, lastplayed, playcount aren't shown) but I'm not sure if this is meant to be displayed or not though.
It says "Assembling game list....... Done!!!"
It says "Now writing [path to gamelist]... Success!!!!"
I can't see any error messages or anything suggesting something has gone wrong.

Let me know if there's anything else you need.
Thanks!

**Comment by muldjord** [comment] 2019-02-25 20:22
> On the part where each game is listed along with its metadata, none of the emulationstation metadata is shown (e.g. platform, Developer, Ages etc are shown, lastplayed, playcount aren't shown) but I'm not sure if this is meant to be displayed or not though.

This is normal, it is not meant to be shown but it should preserve it still. I actually did quite a bit of testing with this, so I find it quite odd that this won't work for you. I will look into it when I get the time.

**Comment by muldjord** [comment] 2019-02-25 20:34
I just reproduced this, I'll look into it.

EDIT: Found the error and fixed it but I will probably rewrite the fix soon. The problem with this is all of the combinations people can do with relative paths on/off and skipping entries yes/no and some entries turning into `<folder>` entries in the ES gamelist.xml.
I use the path to compare the old entries with the new, but this changes depending on the user settings. So I need to take that all into account and I missed a place. I fixed it, but the fix is ugly and I want to refactor some stuff before releasing it. Sorry for the inconvenience.

**Comment by muldjord** [comment] 2019-02-25 22:03
The "ugly" fix is on master now if you want to test it.

**Comment by muldjord** [comment] 2019-02-26 19:48
3.0.5 is now out where this is fixed. I refactored the code and implemented a much cleaner fix that should take care of all combinations. Please test and let me know how it goes, thanks.

**Closed as completed by muldjord** 2019-02-26 19:48 UTC

**Comment by HumanRob** [comment] 2019-03-01 11:50
Just to confirm, I've tested this on 3.0.5 and it works perfectly. Thanks!
