### ISSUE TITLE
Scraping some platforms with multiple sources via retropie script results in no videos in ES

### ISSUE THREAD

**Issue by theshinyknight** [muldjord/skyscraper#236] opened 2020-05-23 17:47 UTC
**Describe the bug**
Videos are not displayed in ES, after running multiple sources for the same romset (arcade, atomiswave, Neogeo, FBA for example). The text for description and other info are displayed, but most if not all the videos are not displayed.

When building the list, I see that most videos have the green YES (arcadedb) text, and I verified in .emulationstation folder that the videos are there, but for some reasons they are not loaded in ES

**To Reproduce**
This is what I did
- installed retropie for Pi4
- ran the internal ES scraper
- installed skyscraper, closed ES, ran it for all the platforms using the default source
- created the list, changed source, ran the scraper again; did that for the remaining sources, creating a new list every time it was done scraping
- restarted the PI4 (I use the comix theme for ES), most platforms seems to show the info and videos, but for arcade, FBA and few other categories, there are no videos at all.

**Special circumstances**
I tried to run the skyscraper via terminal instead from the script to fix this, I ran the command `skyscraper -p [platform] --cache report:missing=all` to generate a missing list and then ran `sjyscraper -p [platform] -s [source] --fromfile [filename]` for each of the missing resources found but this didn't solve the issue. I could see files downloaded but still I see no videos

**Terminal output**
There is no error from the terminal, the scraping is performed correctly (some games are not found but that should not have impact on the games videos that were found). Same when running the gamelist creation.

**Technical information**
 - Skyscraper version: 3.5.2
 - Internet connection: cable
 - OS: retropie (latest for pi4)
 - OS Version 

**Additional context**
Not sure if the issue is related to the retropie script or to something else; other platforms seems to be fine, and the only one affected are the arcade-based ones. Thanks

**Comment by muldjord** [comment] 2020-05-23 19:46
First, please update your Skyscraper version to the latest 3.5.5.

Can you verify that the gamelist.xml files for those platforms contain a path and filename to the videos and that the videos exist at those locations? If that is the case it might be a case of bad video formats. You should then look into the `videoConvertCommand` as documented [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#videoconvertcommandconvertvideosh-i-o). You will need to rescrape the platforms afterwards with cache refresh enabled (it's also in the RetroPie menu) in order to force the conversion to happen.

If your gamelists do not contain the `<video .../>` tags it means you forgot to generate the gamelists after scraping the platforms. You can do so from the RetroPie menu, or by running `Skyscraper -p PLATFORM --flags videos` for each of the platforms that are missing the videos.

**Comment by theshinyknight** [comment] 2020-05-23 20:18
Thanks, just updated to 3.5.5 and trying again

I will also try to wipe the existing cache for one of the platforms that is not working and retrieve the data again, using just arcadedb as source; and see if that works. Then I will try to run a second time on the same platform with a different source and see if the issue reproduce.

the gamelist.xml file is generated and contains the path and filename to the videos. I verified that the video exist at that location (it is the same for all the platforms; they all live in a dot folder under emulationstation; which is the default I believe; I didn't change anything on the output nor in the script. I installed it via the retropie package script installer).

I was not aware that videos has to be converted; I will look into the link you posted.

**Comment by muldjord** [comment] 2020-05-23 20:29
Some of the videos from the sources are not supported by the player they use in ES. Another tip is to try and switch ES to use the omxplayer. That fixes it for some. But I recently added the `videoConvertCommand` to Skyscraper to allow users to convert them on the fly for the same reason.

Good luck with it. I'll close this issue, let me know if you figure out something that works.

**Closed as completed by muldjord** 2020-05-23 20:29 UTC

**Comment by theshinyknight** [comment] 2020-05-23 20:46
Thanks, not sure why the issue is closed if you do not even know why this is happening, but that's OK. Seems nobody else reported the issue so it is not worth keep the report open I guess. 

OMXplayer is switched on; that is the only way to get ES to play videos when running the screensaver with videos; otherwise I would get black screen. 

Will work my way around; in the worst case I can just parse the xml and verify the data on my own files to see what is going on. Thanks

**Comment by muldjord** [comment] 2020-05-23 20:50
I'm not sure what you mean. I already stated that this is caused by the videos delivered by the scraping sources, not Skyscraper. So if anything I am giving support beyond Skyscraper at this point unless you provide me information saying otherwise.

You could try playing some of the videos with mplayer or vlc. This might shed some light on the issues with your current videos.

**Comment by theshinyknight** [comment] 2020-05-23 21:13
> 
> 
> I'm not sure what you mean. I already stated that this is caused by the videos delivered by the scraping sources, not Skyscraper. So if anything I am giving support beyond Skyscraper at this point unless you provide me information saying otherwise.
> 
> You could try playing some of the videos with mplayer or vlc. This might shed some light on the issues with your current videos.

Well, as mentioned, the video is there, the video play  since I verified them; I would not open an issue if this was a problem with the video itself... I did not start writing software recently, been doing that for more than 30 years :)

Closing the issue without knowing what the issue is, does not make sense, especially if you say that you won't give support for anything beyond skyscraper.  If the source of the problem is not clear, make more sense to keep the issue open, instead of just closing it.

Just saying; it is OK to close the issue in the end; I will get my way around the problem, but some other people may not have enough insight, to go through the code and figure out what is going on; so they may benefit from this. Thanks

**Comment by muldjord** [comment] 2020-05-23 21:34
With all due respect, I just did provide you support beyond Skyscraper. And closing an issue does not make it go away. I even asked you to provide information if you figured out what would work.

With your experience you will also know that no project is run the same. I try to keep the open issues on this project quite clean. It is easy to search closed issues.

**Comment by theshinyknight** [comment] 2020-05-24 07:32
Yes, you did provide support about an issue that seems to be outside the realm of the scraper. In short; the scraper retrieve info and media, it did retrieve both info and media, so that cover the basics.

Thanks for going above and beyond; I just wiped the cache and downloaded everything again using the default source. That fixed things, at the cost of multiple GB to download again, but I am happy it is working. Cheers.
