### ISSUE TITLE
Can't scrape "Nester's Funky Bowling (USA)" (Virtual Boy) from ScreenScraper

### ISSUE THREAD

**Issue by joaoluizcarvalho** [muldjord/skyscraper#287] opened 2021-02-16 17:01 UTC
I'm trying to scrape "Nester's Funky Bowling (USA).zip" using: Skyscraper -p virtualboy -s screenscraper

Tried it with unpack="true" and with unpack="false".

I keep getting:
#1/1 (T1) Pass 1 ---- Game 'Nester's Funky Bowling (USA)' not found :( ----

All other games for this system were correctly identified (tried 24 games, this was the only one that got skipped).

Zip file name, .vb file name, file sizes and CRC are exact matches with screenscraper rom entries:
https://www.screenscraper.fr/gameinfos.php?plateforme=11&gameid=4737

Zip filename: Nester's Funky Bowling (USA).zip
Zip size: 643610
Rom filename: Nester's Funky Bowling (USA).vb
Rom size: 2097152
Rom CRC: df4d56b4

My config.ini file has:
inputFolder="/home/joaoluiz/RetroPie/roms"
gamelistFolder="/home/joaoluiz/RetroPie/roms"
mediaFolder="/home/joaoluiz/RetroPie/roms"
cacheFolder="/home/joaoluiz/.skyscraper/cache"
cacheResize="false"
cacheCovers="true"
cacheScreenshots="true"
cacheWheels="true"
cacheMarquees="true"
importFolder="/home/joaoluiz/.skyscraper/import"
unpack="true"
frontend="emulationstation"
emulator=""
videos="true"
symlink="false"
videoSizeLimit="42"
brackets="false"
maxLength="10000"
threads="1"
pretend="false"
unattend="false"
unattendSkip="false"
interactive="false"
forceFilename="false"
verbosity="1"
skipped="false"
maxFails="30"
lang="en"
region="us"
langPrios="en,pt,es,it,fr,de"
regionPrios="us,br,wor,eu,uk,jp"
minMatch="65"
artworkXml="artwork.xml"
relativePaths="false"
hints="false"
subdirs="true"

Skyscraper version: Skyscraper v3.6.7
Internet connection: wifi, 240 Mbps
OS: Linux Mint XFCE 20.1 x86_64 (based on Ubuntu 20.04 LTS)

**Comment by joaoluizcarvalho** [comment] 2021-02-16 17:17
I'm trying to scrape "Nester's Funky Bowling (USA).zip" using: Skyscraper -p virtualboy -s screenscraper

Tried it with unpack="true" and with unpack="false".

I keep getting:
#1/1 (T1) Pass 1 ---- Game 'Nester's Funky Bowling (USA)' not found :( ----

All other games for this system were correctly identified (tried 24 games, this was the only one that got skipped).

Zip file name, .vb file name, file sizes and CRC are exact matches with screenscraper rom entries:
https://www.screenscraper.fr/gameinfos.php?plateforme=11&gameid=4737

Zip filename: Nester's Funky Bowling (USA).zip
Zip size: 643610
Rom filename: Nester's Funky Bowling (USA).vb
Rom size: 2097152
Rom CRC: df4d56b4

My config.ini file has:
inputFolder="/home/joaoluiz/RetroPie/roms"
gamelistFolder="/home/joaoluiz/RetroPie/roms"
mediaFolder="/home/joaoluiz/RetroPie/roms"
cacheFolder="/home/joaoluiz/.skyscraper/cache"
cacheResize="false"
cacheCovers="true"
cacheScreenshots="true"
cacheWheels="true"
cacheMarquees="true"
importFolder="/home/joaoluiz/.skyscraper/import"
unpack="true"
frontend="emulationstation"
emulator=""
videos="true"
symlink="false"
videoSizeLimit="42"
brackets="false"
maxLength="10000"
threads="1"
pretend="false"
unattend="false"
unattendSkip="false"
interactive="false"
forceFilename="false"
verbosity="1"
skipped="false"
maxFails="30"
lang="en"
region="us"
langPrios="en,pt,es,it,fr,de"
regionPrios="us,br,wor,eu,uk,jp"
minMatch="65"
artworkXml="artwork.xml"
relativePaths="false"
hints="false"
subdirs="true"

Skyscraper version: Skyscraper v3.6.7
Internet connection: wifi, 240 Mbps
OS: Linux Mint XFCE 20.1 x86_64 (based on Ubuntu 20.04 LTS)

**Comment by joaoluizcarvalho** [comment] 2021-02-16 18:41
Just had the same issue with this Atari Jaguar rom: https://www.screenscraper.fr/rominfos.php?romid=929810

Zip: Arena Football '95 (World).zip (size: 4194304)
Rom: Arena Football '95 (World).j64 (crc: 199b9d83) (size: 2101561)

Result:
#1/7 (T1) Pass 1 ---- Game 'Arena Football '95 (World)' not found :( ----

**Comment by muldjord** [comment] 2021-02-16 18:57
Please provide the CRC for the zipfiles themselves. That is the one that is most reliably identified. Do your zip files contain more than the .vb file? Then `--unpack` won't work. It might be a combination of those two things that break it.

1. If you zip's CRC is not in the ScreenScraper db, it won't find it unless it matches with an exact filename.
2. If the zip contains more than one file, it won't work with `--unpack`

**Comment by joaoluizcarvalho** [comment] 2021-02-16 19:30
Each zip file contain a single file.

Here are the CRC32 for the roms and their respective zip files.

Nester's Funky Bowling (USA).vb: df4d56b4 (filename and CRC **match** with ScreenScraper entry)
Nester's Funky Bowling (USA).zip: 98e11641 (filename and CRC **match** with ScreenScraper entry)
Entries: https://www.screenscraper.fr/gameinfos.php?gameid=4737&action=onglet&zone=gameinfosroms

Arena Football '95 (World).j64: 199b9d83 (filename and CRC **match** with ScreenScraper entry)
Arena Football '95 (World).zip: c7df97f2 (filename and CRC **not found** in ScreenScraper)
Entries: https://www.screenscraper.fr/gameinfos.php?gameid=200237&action=onglet&zone=gameinfosroms

Regarding "If you zip's CRC is not in the ScreenScraper db, it won't find it unless it matches with an exact filename", wouldn't the unpack="true" option address this?

**Comment by joaoluizcarvalho** [comment] 2021-02-16 19:34
By the way, I also tried scraping the unzipped files, but that didn't work either. Those were the only roms that I was unable to scrape from those two systems.

**Comment by muldjord** [comment] 2021-02-16 19:35
Thanks, I'll see if I can test it and figure out what's going on.

> Regarding "If you zip's CRC is not in the ScreenScraper db, it won't find it unless it matches with an exact filename", wouldn't the unpack="true" option address this?

Yes, but not if there's more than one file in the zip file. Which you don't have, so that's not the issue.

**Comment by muldjord** [comment] 2021-02-16 19:58
Just tried forcing scraping a file with that crc checksum and it works fine for me. In other words, I can't reproduce your issue. You might get it working by forcing a query like this:
```
Skyscraper -p virtualboy -s screenscraper /path/to/virtualboy/Nester\'s\ Funky\ Bowling\ \(USA\).zip --query "crc=98e11641"
```
Please check if that works.

**Comment by muldjord** [comment] 2021-02-16 20:08
Could you also try running the following:
```
Skyscraper -p virtualboy -s screenscraper --verbosity 3 /path/to/virtualboy/Nester\'s\ Funky\ Bowling\ \(USA\).zip
```
And then copy the `Tried with` debug output that shows the query and paste it here so I can see exactly what it tries to ask from the ScreenScraper API.

**Comment by joaoluizcarvalho** [comment] 2021-02-16 21:04
This didn't work, same result: Skyscraper -p virtualboy -s screenscraper ~/RetroPie/roms/virtualboy/Nester\'s\ Funky\ Bowling\ \(USA\).zip --query "crc=98e11641"

And here is the tried with debug output:
'crc=DF4D56B4&md5=0285DC41D75BE8419D12472F20025305&sha1=F4A4C7928F15102CF14C90C5F044E5F7CC7C32F9&romnom=Nester%27s%20Funky%20Bowling%20(USA).zip&romtaille=643792'
Platform: virtualboy

**Comment by joaoluizcarvalho** [comment] 2021-02-16 21:06
And here is the debug output for the Atari Jaguar rom:
'crc=199B9D83&md5=A73C0E4F3A0D3DE6C40688FF66EB4B6E&sha1=542063A5B27659781A85821F61E85CD89EA59AB3&romnom=Arena%20Football%20%2795%20(World).zip&romtaille=2101741'
Platform: atarijaguar

**Comment by muldjord** [comment] 2021-02-16 21:44
I'm at a loss. I just tried with your exact query `crc=DF4D56B4&md5=0285DC41D75BE8419D12472F20025305&sha1=F4A4C7928F15102CF14C90C5F044E5F7CC7C32F9&romnom=Nester%27s%20Funky%20Bowling%20(USA).zip&romtaille=643792` and it worked fine, found the game perfectly.

**Comment by muldjord** [comment] 2021-02-16 22:08
Quick comment on your `config.ini`. I'm not sure if that is causing this issue, but you have *a lot* of configs set in there that aren't needed. For instance, you have set all of the paths to the paths that are already default. So you can remove all of those. I would recommend removing all of the options and retrying with this command-line:
```
Skyscraper -p virtualboy -s screenscraper virtualboy/Nester's\ Funky\ Bowling\ (USA).zip --verbosity 3 --query "crc=DF4D56B4&md5=0285DC41D75BE8419D12472F20025305&sha1=F4A4C7928F15102CF14C90C5F044E5F7CC7C32F9&romnom=Nester%27s%20Funky%20Bowling%20(USA).zip&romtaille=643792"
```
Lastly, did you remember to add your ScreenScraper credentials to your config.ini? You need a  `[screenscraper]` section with credentials. Otherwise that might be the issue itself as unregistered use is very unstable.

**Comment by joaoluizcarvalho** [comment] 2021-02-17 00:08
Following your suggestion, after some tests, I learned that the line that was causing the problem was this one:

`regionPrios="us,br,wor,eu,uk,jp"`

If i use my old config.ini, but remove that line, I can simply do `Skyscraper -p virtualboy -s screenscraper` and it works.

That also fixed the problem with the Atari Jaguar game.

Is there a way to specify region priority without having this issue?

**Comment by muldjord** [comment] 2021-02-17 07:47
`regionPrios` overrides the internal region priority list completely. So if it doesn't find any of those, it probably won't give back a result. But if you use `region="REGION"` instead, it will add it to the existing internal priority list. Either way, you probably don't need those, unless you want to force a region. Skyscraper auto-detects the region from the filename. So, for instance, `(USA)` in the filename will automatically be added as `us` and prioritized for that file.

What I don't understand is that you already had `us` set in your `regionPrios` config. So it should have found it even though you had it overridden. Hopefully I will be able to make it fail similarly by simly setting `regionPrios="us,br,wor,eu,uk,jp"` in my own `config.ini`. Then I can try to figure out why it didn't work.

**Comment by muldjord** [comment] 2021-02-17 15:07
Ok, so I've found the reason as well now. The game `Nester's Funky Bowling` does not have a `us` name entry at ScreenScraper. It only has an `ss` region listing, which is their internal region that is basically a fake region they use sometimes. The `ss` simply stands for `ScreenScraper`. If you change it to `regionPrios="us,br,wor,eu,uk,jp,ss"` it will work.

So, to summarize: Skyscraper works as expected, but ScreenScraper apparently only has `ss` names for a small number of their games. The workaround for the current version of Skyscraper is as described above. I will also add `ss` as the last entry on the default regionPrios list (which is used if no user-defined one is found in config.ini). This should ensure this *will just work* in future releases.

EDIT: I just noticed I actually have `ss` in the default one already in the current version of Skyscraper, so no need to change that. Which is also why it works for you when the regionPrios is unset of course.

**Comment by joaoluizcarvalho** [comment] 2021-02-19 02:11
That makes sense, thank you!

By the way, according to [this](https://github.com/muldjord/skyscraper/blob/master/docs/REGIONS.md), region `ca` is not included in the default region priority. Perhaps it would be a good idea to include that as well.

On an unrelated question, I noticed you included an "skipexistingmedia" option, but I couldn't find any documentation about what it does. I tried Skyscraper --help and the documentation on github (readme.md, configini.md). Could you please point me to some information about that new feature? Thank you in advance!

And thank you for taking your time to help me with this issue. I think it is all clear now! :)

**Comment by muldjord** [comment] 2021-02-19 12:58
Sure, I will add `ca`, no problem.

That option has been moved into the `--flags` option and separated out per media type. They are all documented [here](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md#skipexistingcovers). The options are only relevant when generating a gamelist.

**Comment by joaoluizcarvalho** [comment] 2021-02-24 22:55
If I want to add those flags to my config.ini, would something like `skipexistingvideos="true"` work?

**Comment by muldjord** [comment] 2021-02-25 19:36
All possible flags are documented [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md) including what sections they can be applied to.

**Comment by joaoluizcarvalho** [comment] 2021-02-26 01:43
I have another region-related issue/question.

I am not sure if this is a bug, but I was trying to scrape the japanese boxart and wheel for Sonic CD from ScreenScraper without success. Skyscraper kept downloading the US art, even if I set `regionPrios="jp"` in `config.ini`. Then I realized I also had `region="us"` in my `config.ini`. After I removed `region="us"`, Skyscraper downloaded the japanese art.

Coud you please explain the difference between `region` and `regionPrios`? What happens when the first country listed in `regionPrios` is not the same as the country in `region`?

Tried with: 'crc=21483699&md5=D80063F5EBE39B35479A7B564232FA3F&sha1=99C891C4849024DB36303EAB191C2F1E6FCE3DB4&romnom=Sonic%20The%20Hedgehog%20CD%20(Japan).chd&romtaille=338396806'
Platform: segacd

**Comment by muldjord** [comment] 2021-02-26 21:45
Both are explained [here](https://github.com/muldjord/skyscraper/blob/master/docs/REGIONS.md) (it's not a bug). Let me know if it's unclear.

EDIT: Looking over my documentation I think I can clarify it. So I'll update it.

EDIT2: Region and language documentation has now been almost completely rewritten. Should be a lot clearer how it works now.

**Comment by joaoluizcarvalho** [comment] 2021-02-28 19:53
Thank you. I had read Regions.md before I asked, but that information wasn't too clear then. It is a lot more clear now.

I assume `--region REGION` or `region="REGION"` overrides the auto-detected region? If that is so, then I suggest adding that information to the documentation.

Suppose I'm scraping a rom named `"Game Name (Europe).zip"`, and I use `region="jp"`, and also `regionPrios="us,wor,ss"`, which regions would have top priority?

Again, thank you for all your had work on Skyscraper. Being able to see box arts and videos for the games in my collection has completely changed my experience with emulation. I tried other scrapers before, but Skyscraper is my favorite, hands down. I want to make sure I know how to use it to its full potential, so I really appreciate you taking your time to answer my questions.

Cheers!

**Comment by muldjord** [comment] 2021-02-28 20:59
> I assume --region REGION or region="REGION" overrides the auto-detected region? If that is so, then I suggest adding that information to the documentation.

Yes, it has now been clarified [here](https://github.com/muldjord/skyscraper/blob/master/docs/REGIONS.md#default-region-prioritization).

> Suppose I'm scraping a rom named "Game Name (Europe).zip", and I use region="jp", and also regionPrios="us,wor,ss", which regions would have top priority?

There's no need to ever use both. `region="REGION"` is used if you want to specify a single region that should be added to the top internal list, which is probably what most people want to do.
`regionPrios="REGION,LIST"` is there to overwrite it entirely, in which case you would just include the one you wanted from `region="REGION"` to begin with.

EDIT: Found an error in the docs. I previously has a note warning that using `regionPrios="REGION,LIST"` would overwrite the auto-detected region. It does not! I don't know why I wrote that. The auto-detected region will *always* be added to the top of the list no matter how it's configured with `region` or `regionPrios`.

> I tried other scrapers before, but Skyscraper is my favorite, hands down. I want to make sure I know how to use it to its full potential, so I really appreciate you taking your time to answer my questions.

Glad you like it, I've spend hundreds, if not thousands, of hours on it, so I'm glad people find it useful. I don't normally answer questions on github, but in this case it was clearly a matter of documentation that needed clarification, so it makes sense. Normally I prefer people asking question on the RetroPie forums. There are so many Skyscraper users nowadays that plenty of people can help. I often pop in there to answer questions myself. The difference being that I then *decide* to provide personal support. On here it feels very directed at me. So it's basically only for bugs and feature requests. But again, in this case it makes sense to me, as the region documenation clearly needed a bit of a rework.

**Comment by joaoluizcarvalho** [comment] 2021-03-02 01:33
> Yes, it has now been clarified [here](https://github.com/muldjord/skyscraper/blob/master/docs/REGIONS.md#default-region-prioritization).

Ok, the updated doc states the auto-detected region has priority over `region="REGION"`. If that is so, then I don't understand why I was unable to scrape the japanese Sonic CD art when `region="us"` was used? The filename had "(Japan)" in it (see my "tried with" debug output above), so I assume "jp" should have higher priority than "us"...

> There's no need to ever use both. `region="REGION"` is used if you want to specify a single region that should be added to the top internal list, which is probably what most people want to do.
> `regionPrios="REGION,LIST"` is there to overwrite it entirely, in which case you would just include the one you wanted from `region="REGION"` to begin with.

Ok. But the thing is --- by mistake --- I scraped some systems using something like what I described in my question from yesterday (I defined both region and regionPrios, with conflicting regions). I thought things went as I intended anyway, but then this issue with Sonic CD (Japan) got me confused. Depending on your answer, I may decide to re-scrape those systems.

**Comment by muldjord** [comment] 2021-03-02 08:36
> I defined both region and regionPrios, with conflicting regions

In that case the region you put it `region="REGION"` was added to the top of the ones you defined in `regionPrios="REGION,LIST"`. Having conflicting regions is not an issue. They can be on the list several time without problems. It's only the order that's important.

> Ok, the updated doc states the auto-detected region has priority over region="REGION"

Yes, every time a new game is scraped, the file name is scanned for a region. If one is found it is then prepended to region priority list that has been put together from `region` and `regionPrios` prior.

This is the code:
```
  // Reset region priorities to original list from Settings
  regionPrios = config->regionPrios;
  // Autodetect region and append to region priorities
  if(info.fileName().indexOf("(") != -1 && config->region.isEmpty()) {
    QString regionString = info.fileName().toLower().mid(info.fileName().indexOf("("), info.fileName().length());
    if(regionString.contains("europe") || regionString.contains("(e)")) {
      regionPrios.prepend("eu");
    }
    if(regionString.contains("usa") || regionString.contains("(u)")) {
      regionPrios.prepend("us");
    }
    if(regionString.contains("world")) {
      regionPrios.prepend("wor");
    }
    if(regionString.contains("japan") || regionString.contains("(j)")) {
      regionPrios.prepend("jp");
    }
    if(regionString.contains("brazil")) {
      regionPrios.prepend("br");
    }
    if(regionString.contains("korea")) {
      regionPrios.prepend("kr");
    }
    if(regionString.contains("taiwan")) {
      regionPrios.prepend("tw");
    }
    if(regionString.contains("france")) {
      regionPrios.prepend("fr");
    }
    if(regionString.contains("germany")) {
      regionPrios.prepend("de");
    }
    if(regionString.contains("italy")) {
      regionPrios.prepend("it");
    }
    if(regionString.contains("spain")) {
      regionPrios.prepend("sp");
    }
    if(regionString.contains("china")) {
      regionPrios.prepend("cn");
    }
    if(regionString.contains("australia")) {
      regionPrios.prepend("au");
    }
    if(regionString.contains("sweden")) {
      regionPrios.prepend("se");
    }
    if(regionString.contains("canada")) {
      regionPrios.prepend("ca");
    }
    if(regionString.contains("netherlands")) {
      regionPrios.prepend("nl");
    }
    if(regionString.contains("denmark")) {
      regionPrios.prepend("dk");
    }
    if(regionString.contains("asia")) {
      regionPrios.prepend("asi");
    }
  }
```
As you can see it starts off by copying the original priority list (made up from `region` and `regionPrios`) to a temporary list only used by the current game. It then looks for a region in the file name and prepends it if one is found. For the next game, it does this all over again, starting with the original list.

And here's the initial loading of the region configs:
```
  // Load single custom region
  if(!config.region.isEmpty()) {
    config.regionPrios.append(config.region);
  }

  // Load custom region prioritizations
  if(!config.regionPriosStr.isEmpty()) {
    for(const auto &region: config.regionPriosStr.split(",")) {
      config.regionPrios.append(region.trimmed());
    }
  } else {
    config.regionPrios.append("eu");
    config.regionPrios.append("us");
    config.regionPrios.append("ss");
    config.regionPrios.append("uk");
    config.regionPrios.append("wor");
    config.regionPrios.append("jp");
    config.regionPrios.append("au");
    config.regionPrios.append("ame");
    config.regionPrios.append("de");
    config.regionPrios.append("cus");
    config.regionPrios.append("cn");
    config.regionPrios.append("kr");
    config.regionPrios.append("asi");
    config.regionPrios.append("br");
    config.regionPrios.append("sp");
    config.regionPrios.append("fr");
    config.regionPrios.append("gr");
    config.regionPrios.append("it");
    config.regionPrios.append("no");
    config.regionPrios.append("dk");
    config.regionPrios.append("nz");
    config.regionPrios.append("nl");
    config.regionPrios.append("pl");
    config.regionPrios.append("ru");
    config.regionPrios.append("se");
    config.regionPrios.append("tw");
    config.regionPrios.append("ca");
  }
```
It first checks to see if `region` is configured. It then adds that to the list. Then it checks if user has set anything in `regionPrios`. If so, it add those to the list. If none is set in `regionPrios` it will append the default list as documented.

**Comment by muldjord** [comment] 2021-03-02 13:48
> Ok, the updated doc states the auto-detected region has priority over region="REGION". If that is so, then I don't understand why I was unable to scrape the japanese Sonic CD art when region="us" was used? The filename had "(Japan)" in it (see my "tried with" debug output above), so I assume "jp" should have higher priority than "us"...

Been testing this, and something isn't right... I need to look into this further. Stay tuned.

**Comment by joaoluizcarvalho** [comment] 2021-03-02 13:49
Thank you! I have two questions:

1) Is `regionString.contains` case-sensitive?

2) I'm probably wrong, but from looking at the code, it seems to me that the section starting at `//Autodetect region and append to region priorities` is only executed if `region` is empty.

**Comment by muldjord** [comment] 2021-03-02 13:51
Ah, yes, just combed the code again. I'm sorry, it's been a long time since I've messed with this code. The auto-detect is *only* used if `region="REGION"` is NOT set. So I need to update the documentation again.

**Comment by muldjord** [comment] 2021-03-02 13:57
[Updated](https://github.com/muldjord/skyscraper/blob/master/docs/REGIONS.md#default-region-prioritization) docs to reflect this. It should be correct now.

**Comment by joaoluizcarvalho** [comment] 2021-03-02 14:06
Thank you! I think [this](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md#--region-code) still needs review, as it still says "Any file name auto-detected region will still have top priority, even when this config is used".

**Comment by muldjord** [comment] 2021-03-02 14:09
Thanks, hopefully that is the only remaining place that needed updating.

**Comment by joaoluizcarvalho** [comment] 2021-03-02 14:14
Perfect! You are the best! Feel free to close this if you will.

**Comment by muldjord** [comment] 2021-03-02 14:40
Closing. Feels good having the region docs updated, thanks.

**Closed as completed by muldjord** 2021-03-02 14:40 UTC
