### ISSUE TITLE
add support for naomi

### ISSUE THREAD

**Issue by elobato92** [muldjord/skyscraper#228] opened 2020-05-17 07:12 UTC
**Describe the feature / request**
I have some Naomi roms that I would like to scrape using this tool.  Screenscraper.fr has a large library of Naomi metadata to pull from. 

**Additional context**
I can't seem to find a cli tool that supports scraping naomi data, so I feel like this would be an especially useful feature.

**Comment by muldjord** [comment] 2020-05-17 08:01
EDIT: Just looked into this a bit further. The `naomi` platform on ScreenScraper is an child-platform of `mame`. What you can do is simply place your roms in the `arcade` subfolder and scrape them with `-p arcade`. Since it is a child-platform of `mame` that should work.

**Comment by elobato92** [comment] 2020-05-17 15:26
Thank you so much for digging! I'll try that out today and report back

**Comment by elobato92** [comment] 2020-05-17 20:44
I tried a few methods with no success.
Threw the roms into the arcade folder and scraped with -p arcade, nothing
scrapped the naomi folder with the -p arcade arcade flag, nothing
tried scraping with the mame flags, and nothing for all of them

I was able to scrape the data using Skraper, so I can at least verify that the roms should be getting picked up against the screescraper.fr DB.

**Comment by muldjord** [comment] 2020-05-17 21:37
> I was able to scrape the data using Skraper, so I can at least verify that the roms should be getting picked up against the screescraper.fr DB.

That's good to know for my further research. I'll look into it and get back to you.

**Comment by muldjord** [comment] 2020-05-19 15:22
I found a way to make this work. If you add the following to the `/home/USER/.skyscraper/config.ini` file it works for me:
```
[arcade]
addExtensions="*.bin *.dat"
```
If your files have a different extension than those, add those instead. And then add the files to your arcade folder and scrape them with `Skyscraper -p arcade -s screenscraper --refresh`. Could you test this please?

**Comment by mnakalay** [comment] 2021-04-11 20:02
Hello. Sorry to revive this as it's almost a year's old but I'm in a different situation.
For now, I'm scrapping Naomi games by doing as you said and putting them in the arcade folder. That works flawlessly.

The problem is I can't seem to make the games work with the Mame emulator so I'm using flycast to play them. Flycast, in RetroPie, is only available for Dreamcast. So I set up a Naomi folder to act as a Dreamcast folder and that works well.

So when I want to scrap my games, I have to put them in the arcade folder then grab the resulting gamelist.xml file and copy and paste it to the Naomi folder, merging it with the existing one.

It's a bit of a pain, to be honest, so I would totally support adding Naomi/Atomiswave to the list.

Thank you :)

**Comment by muldjord** [comment] 2021-04-12 14:17
Have you tried simply plopping them into the dreamcast folder?

**Comment by mnakalay** [comment] 2021-04-12 20:02
Yes that was my first thought but it didn't work. Those roms are arcade roms so in the dreamcast folder they're not found. They have to follow specific naming conventions like any MAME rom so the name is not a match for any dreamcast game and neither is the checksum.
They have to be in an arcade folder, either name or fba or custom folders like naomi and atomiswave

**Comment by muldjord** [comment] 2021-04-12 21:10
I think I'll add this, it's been requested a couple times now. I'll add it as `naomi` and simply make it a copy of the existing `arcade` platform with a few more extensions added per default. Does thats sound ok?

**Comment by muldjord** [comment] 2021-04-12 21:42
3.6.10 out now! `naomi` and `atomiswave` now added as platforms. Please test, closing this now, reopening if errors reported.

**Closed as completed by muldjord** 2021-04-12 21:42 UTC

**Comment by mnakalay** [comment] 2021-04-12 22:09
I tested it. I put my naomi and atomiswav roms in the naomi folder and it all got scrapped perfectly. This is great thank you!

**Comment by muldjord** [comment] 2021-04-12 22:44
Awesome, thanks for testing!
