### ISSUE TITLE
ScreenScraper APIv2 returned invalid / empty Json 

### ISSUE THREAD

**Issue by ghost** [muldjord/skyscraper#286] opened 2021-02-16 05:34 UTC
Screenscraper told me to upload this file.
Here you go

[screenscraper_error.zip](https://github.com/muldjord/skyscraper/files/5986334/screenscraper_error.zip)

**Comment by palmerj** [comment] 2021-02-16 07:29
duplicate of #281

**Comment by muldjord** [comment] 2021-02-16 08:02
Yeah, I think I'll remove the message that tells the user to upload these files. 99% of the time it is because their service is down. But thanks anyway.

**Comment by palmerj** [comment] 2021-02-16 09:01
Do you know if someone has a gameid to rom or game name mapping? That would help for the moment while the API service is down.

**Comment by muldjord** [comment] 2021-02-16 09:15
I'm not sure I understand the question, can you elaborate?

**Comment by palmerj** [comment] 2021-02-16 10:10
Well many people in the past have downloaded data from ScreenScraper to generate local resources such as gamelist.xml. In these XML files there should be a gamed which is sourced from ScreenScraper. If someone could publish those (old is ok for my use case), I could use those gameid to scrape media from the website now. i.e https://www.screenscraper.fr/image.php?gameid=40130&media=sstitle&hd=0&region=wor&num=&version=&maxwidth=338&maxheight=190

**Comment by muldjord** [comment] 2021-02-16 10:38
Skyscraper doesn't cache those id's. Collecting the information and distributing it with game data is a bit of a grey area as the ownership of that data is hard to pin-point (does ScreenScraper own it? Does the user who submitted it? Can you even own game data such as "who developed this game"?). Especially the game descriptions that are quite authored. So it's not something I would ever delve into with Skyscraper. It's simply a wasps nest of political problems.

You might be able to get the mappings by contacting ScreenScraper though. I dunno. :)

**Comment by palmerj** [comment] 2021-02-16 19:26
Ok thanks. I guess we just need that API to work. Has it been working at all in recent times? I haven't been able to access it in the last 2 months, and can't sign up to their forums to even ask what is going on.

**Comment by muldjord** [comment] 2021-02-16 19:33
It worked when I've been testing it over the last couple of weeks. There was one day with som downtime I think, but other than that I haven't had issues. I don't think they use their forums much. I'd go on their Discord instead.

**Comment by palmerj** [comment] 2021-02-16 21:05
Ok thanks.

**Closed as completed** 2021-04-06 20:32 UTC
