### ISSUE TITLE
Atari 2600 & C64 scraping always freezes

### ISSUE THREAD

**Issue by PeterDeGuardian** [muldjord/skyscraper#33] opened 2018-07-07 08:01 UTC
Hi,
When i try to scrape Atari 2600 roms or C64 disks Skyscraper always freezes after some time. I tried booth 3-4 times, but booth always freezes. It is not at scraping the same rom/disk, it is always at diffent times (e.g. sometime at the 905s rom, next time at the 134s rom).

What it do: simply stops operation. You only see the output of the last rom + a elapsed time/estimated time line. No error, only didn‘t do anything anymore.

I am running the latest retropie image and the latest Skyscraper. My connection is WiFi.
We are talking about 4000 Atari 2600 Roms and 50000 C64 Disks & co.

And it is permanent. I can reproduce the error every time.....but it stops working at different times in the scraping process.
Other scrapes with big volumes of data (like Amstrad CPC, also about 5000 disks or Mame worked without any problem).

I am using skyscraper in simple mode.

**Comment by muldjord** [comment] 2018-07-07 20:10
Thank you for the detailed description. This issue seems to pop up from time to time, and I have never been able to reproduce it. So basically I can't fix it, since I don't have the issue myself.

- Is your wifi stable? How far is your pi from the ap? Is it a pi 3 model b? They are known for unstable wifi, which would cause Skyscraper to hang just as you describe. That is my best guess.

**Comment by muldjord** [comment] 2018-08-06 07:08
Closed from lack of response.

**Comment by Pumph0use** [comment] 2018-08-19 04:00
I am having the same issue as listed here. Except mine always freezes on the at 345 out of 346 files. The 346th file never gets processed, and its only for atari2600. Same scenario, just stops and stays where it was displaying a remaining/estimated time.

**Comment by muldjord** [comment] 2018-08-19 07:02
Is it ALWAYS at 345? Because that means I should be able to reproduce it. Please tell me which EXACT filename it just scraped, and which filename would be the next filename it should have scraped. :)

**Comment by Pumph0use** [comment] 2018-08-19 13:42
Hey Lars,

I had a giant bash script running for every platform overnight. I am going
to run a few different tests now that it is over to see how far I can
narrow it down for you. I will get back to you by tonight with the results.

Thanks in advance.

**Comment by muldjord** [comment] 2018-09-16 12:45
Any news on this? Otherwise I'll close the issue.

**Closed as completed** 2018-09-18 16:19 UTC
