### ISSUE TITLE
Covers not downloading

### ISSUE THREAD

**Issue by Obspogon** [muldjord/skyscraper#336] opened 2022-03-10 02:56 UTC
**Describe the bug**
[Scraper is not downloading any covers for all games.] 

**To Reproduce**
[i have scrapecovers as true in the config. I'm exporting to the Pegasus frontend and scraping from screenscraper and thegamesdb]

**Technical information**
 - Skyscraper version: Current version
 - Internet connection: [wifi]
 - OS: Linux mint
 - OS Version: current

**Additional context**
I pass the onlymissing flag. I did not in the first run, but even then the covers weren't downloaded. The wheels aren't Downloaded either, but I left that out of the config file

**Comment by muldjord** [comment] 2022-03-10 06:56
Hi, I suggest asking this on the RetroPie forums where people can help you. This is likely not a bug. Thanks. Closing.

**Closed as completed by muldjord** 2022-03-10 06:56 UTC

**Comment by lucianthorr** [comment] 2025-10-27 02:40
@Obspogon I have been trying to learn how Skyscraper and Pegasus work together, independent of RetroPie, and ran into a similar issue.  It's probably not a bug but at least it was easy for me to misunderstand.
To fix it, I needed to add a `cover` output object into the artwork.xml, use the [second example](https://github.com/muldjord/skyscraper/blob/03d8d657d1ea3dfc5d3b1047922b76971bdf5ff5/artwork.xml.example2).
Previously, I was just using the default artwork.xml, which generated a screenshot and copied over the raw marquee and video. 

I know this is old but maybe it'll help anyone in the future that's in the same boat.
