### ISSUE TITLE
Scraping Sega Saturn cue+bin results in duplicate gamelist entries

### ISSUE THREAD

**Issue by joaoluizcarvalho** [muldjord/skyscraper#200] opened 2020-03-18 23:14 UTC
When I scrape Sega Saturn games in cue+bin format, Skyscraper tries to scrape the .cue file, but it also tries to scrape each .bin file. This results in multiple gamelist entries for each game (one entry for the .cue file and one entry for each .bin file).

I could probably fix that by adding extensions="*.cue" to my config.ini file, but shouldn't Skyscraper scrape only the .cue files?

My Sega CD, PS1, and PC Engine CD games are also cue+bin, but I didn't experience duplicate entries with those systems (only the .cue files are scraped for those systems). I only had this issue with the Sega Saturn games.

**Comment by muldjord** [comment] 2020-03-18 23:21
Yeah, I'm aware of this issue (it's been reported before, although not on Github it seems). As I recall the problem is that some Saturn roms are in `.bin` (not paired with a cd-rom image). So I had to include both. Basically I would recommend just adding your own custom `[saturn]` section in config.ini like so:
```
[saturn]
extensions="*.this *.that"
```
And just add whatever files you use.

EDIT: Hm, maybe I should just remove `*.bin` from Saturn. It would seem to me that the issue you report is bigger than the niche of using `*.bin` files by themselves.

**Comment by muldjord** [comment] 2020-03-18 23:35
I've decided to remove `*.bin` from the `saturn` platform. It will be default in the next Skyscraper release. For now, just use a custom `extensions=`. Thank you for pointing it out. Closing.

**Closed as completed by muldjord** 2020-03-18 23:35 UTC
