### ISSUE TITLE
Roms on network drive so not saving scrapped files? 

### ISSUE THREAD

**Issue by rrbenitez05** [muldjord/skyscraper#290] opened 2021-02-23 23:43 UTC
Hello I'm running retropie v4.7.1 on a raspberry pie 4 and the way I have my retropie setup is that its pulling roms from a network drive. Would this have any affect on how skyscrapper works as in saving those game list etc since the roms are not in the default drive? When ran skyscraper I was getting this error

The erroneous answer was written to '/home/USER/.skyscraper/screenscraper_error.jason' 

I did run skyscraper several times and it was scraping titles but I don't know if the system couldn't see the xml files because the roms are on a network drive an not in the default location.

Any suggestions and help is appreciated.

**Comment by muldjord** [comment] 2021-02-24 15:55
Hi, this is a duplicate of https://github.com/muldjord/skyscraper/issues/281

If you need help using Skyscraper, please ask your questions on the RetroPie forums, thanks.

**Closed as completed by muldjord** 2021-02-24 15:55 UTC
