### ISSUE TITLE
Some screenscraper images fail to resize, causing zero length files. libpng error: length does not match profile [FIXED]

### ISSUE THREAD

**Issue by jacrify** [muldjord/skyscraper#216] opened 2020-04-17 22:57 UTC
**Describe the bug**
Certain images scraped from screenscraper fail to be resized. This results in zero byte images in the cache. This in turn results in zero byte generated images, and also seems to cause the existing gamelist.xml to be ignored.

**To Reproduce**
Happens for a handful (>50 roms) only. For an example see the wheel of "Turrican (USA).zip" on pcengine.

1. Clear all resources in cache:  
	Skyscraper -p pcengine   "Turrican (USA).zip" --cache edit   
	followed by D, q
2. Validate cache: 
	Skyscraper -p pcengine   "Turrican (USA).zip" --cache validate
3. Scrape from skyscraper: 
	Skyscraper -p pcengine   "Turrican (USA).zip" -s screenscraper
	Scrapes successfully, with message "libpng error: profile 'sRGB IEC61966-2.1': 0h: length does not match profile"
cache/pcengine/wheels/screenscraper/d3f4f4ae08a44283458b3cdd6b53c025df9e754f.png is now 0 bytes
4. Remove old gamelist. I did this manually to reproduce cleanly, but there is something odd about the what this bug does to gamelist generation- I believe I have seen it cause the old gamelist to be read. However I haven't cleanly reproduced this behaviour.
5. Generate gamelist:
	Skyscraper -p pcengine   "Turrican (USA).zip"
	Generates with message "libpng error: profile 'Custom': 0h: length does not match profile"
	roms/pcengine/media/screenshots/Turrican (USA).png is 0 bytes

Rerunning the above, but adding "--noresize" to step 3 removes the libpng errors, and results in clean outputs.
	

**Special circumstances**

Running on Mac?

**Terminal output**

As above. Can give full logs if required

**Technical information**
 - Skyscraper version: 3.4.8, cleanly rebuilt just for this test
 - Internet connection: cable
 - OS: Mac OS
 - OS Version: 10.15.4

**Additional context**
Great scraper.

**Comment by jacrify** [comment] 2020-04-18 01:49
Correction to the above. Running with --noresize does not fix errors for all images. Specifically, I did the following:
1. Deleted all zero length images in cache : find ./ -type f -size 0 -exec rm -f {} \;
2. Ran --cache validate on all platforms
3. Rescraped pcengine against screenscraper, using --noresize. Only the missing zero length files were redownloaded
4. Regenerated gamelist

Result is that for some file (eg "Turrican (USA).zip") I have working art. However some others (eg "Legendary Axe II (USA).zip" I still get 0 length screenshots as output, "libpng error: profile 'Custom': 4000000h: length does not match profile" error during gamelist generation. However I have no zero length files in cache for this rom.

**Comment by jacrify** [comment] 2020-04-18 02:54
Here's the unresized wheel for Turrican (USA) as an example of a file I think causes errors.
[d3f4f4ae08a44283458b3cdd6b53c025df9e754f.zip](https://github.com/muldjord/skyscraper/files/4495936/d3f4f4ae08a44283458b3cdd6b53c025df9e754f.zip)

**Comment by muldjord** [comment] 2020-04-18 07:50
I am unable to reproduce this (Turrican scrapes fine with no 0 byte artwork and no libpng errors) but it has some resemblance to this: https://github.com/muldjord/skyscraper/issues/215

I don't call libpng manually anywhere, this is all done through Qt's framework, meaning for such an error to occur, it would be a Qt bug (which is the one using libpng). And I very highly doubt that is the case. Or, perhaps, this is a Mac related issue where you have one of the bad libpng's. I recall having read about that some time back. I do not own a Mac and therefore can't test it.

I already do checks on the images before saving them. Both for the cache and when generating the gamelist artwork. I will do a check on my Pi for 0 byte images. If I don't have any, I will have to write this off as a faulty libpng on your end, or a corrupt SD card or disk.

EDIT: Ran a check on my Pi for 0 byte cached images. I do not have a single one out of several thousands, so I'm gonna have to write this off as circumstantial for your system. Let me know if you have further information that would point to the contrary.

**Comment by jacrify** [comment] 2020-04-18 23:49
I've checked my qt and libpng versions, and I'm running the latest of each. I don't believe this is a corrupt disk (I'm writing the images to a mac SSD) as the same images fail each time. It's probably a local libpng issue :(

Would you consider accepting a patch? Whatever the root cause is, the thing that make this nasty is that Skyscraper is not checking the result of Qt Image.save, resulting in zero byte images sitting in the cache. This is turn results in composition failures. A better result would be for the images not to be in the cache in the first place- then for scenarios like this users could replace the missing images with results from other scrapers.

I know this is just my issue, but there may be other scenarios that cause Image.save to fail.

I've tested this locally and it works. Apologies I'm not a github expert-patch is below. Happy to submit this back to this repo if required. There are probably other image.save instances in the code base that could be checked- however this one is an easy change as you already have the okToAppend flag.

https://github.com/muldjord/skyscraper/compare/master...jacrify:jacrify-patch-1-1?expand=1

**Comment by muldjord** [comment] 2020-04-19 07:20
> the thing that make this nasty is that Skyscraper is not checking the result of Qt Image.save

I do a test when reading the image data, but you are right, since I rewrote this a little while back, I actually forgot to re-implement a check on the `.save` itself. I will re-implement this. Thank you for letting me know.

**Comment by jacrify** [comment] 2020-04-19 07:31
No problem. The patch I posted above didn't actually fix the totality of my libpng issues- it got rid of some of them, but there must still be scenarios where scraped images don't go through the resize block, as I still have some images failing on composition (ie generate zero length files) with corresponding libpng errors. I've given up on mac as a platform and shifted the whole cache to my retropie- it's somewhat slower to scrape and copy, but more deterministic.

**Comment by muldjord** [comment] 2020-04-19 07:42
Yes, I will go a bit beyond the `.save` check in your patch, but that will be part of it. I will see if I can avoid all of the issues you are seeing. But it is unfortunate that this is seemingly all down to a faulty libpng inside Qt. It means that Mac users would be loosing out on data compared to when doing it on a Pi. And there's not really a good way to fix that.

**Comment by jacrify** [comment] 2020-04-19 07:52
I've done some googling on the various libpng errors I'm seeing, and they seem to indicate that later versions of libpng are stricter than older versions. The mac is using 1.6.37 of png, but I haven't been able to work out what version the pi is using. Might be worth checking this just in case the pi is using a lower version- if so there is a fairly insidious breaking bug in the pipeline...

**Comment by muldjord** [comment] 2020-04-19 08:15
Yeah, I just did the same research... What worries me is if Qt is giving back bool's that indicate success when it shouldn't. But I will do what I can with what they provide to make sure the image is sound before accepting it in the cache.

**Comment by muldjord** [comment] 2020-04-19 11:49
I just noticed something in OP. You say the file in the cache is called `cache/pcengine/wheels/screenscraper/d3f4f4ae08a44283458b3cdd6b53c025df9e754f.png`... This seems odd to me, since I no longer use extensions for these files, and it will automatically remove any files with the `.png` extension when the game is rescraped. If you do indeed have a `.png` file in the cache, it was made with an older version of Skyscraper.

The new checks are now in place and on master, in case you want to test it.

**Comment by muldjord** [comment] 2020-04-21 20:42
3.4.10 now out with more checks in place.

**Closed as completed** 2020-04-25 14:48 UTC
